swagger: "2.0"
info:
  title: API for tailieubk
  version: 1.0.0

schemes:
  - http
  - https
host: localhost:3000
basePath: /api/v1

tags:
  - name: Test
    description: Testing tag
  - name: Document
    description: Tag contains document apis
  - name: School
    description: Tag contains school apis
  - name: Subject
    description: Tag contains subject apis
  - name: Faculty
    description: Tag contains faculty apis
  - name: Tag
    description: Tag contains tag apis

definitions:
  SampleEnum:
    type: string
    enum:
      - LUAN
      - DUC
      - HUY
  SampleResponse:
    type: object
    properties:
      message:
        type: string

paths:
  /sample:
    get:
      summary: Sample API for demo
      tags:
        - Test
      operationId: sample
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/SampleResponse'